### ISSUE TITLE
Acquistion dump memory

### ISSUE THREAD

**Issue by dfirtest** [fox-it/OpenSSH-Session-Key-Recovery#5]
Hello,

I would like to know if there is a special manipulation for the memory dump to do?
I tested with Lime or the debug mode of Virtualbox and especially on a multitude of different Debian/Ubuntu versions (Debian 9,10,11 or Ubuntu 18.04 and 20.04).

I never manage to retrieve the values with the plugin openssh_sessionkeys (Adress, PID, Name, Key, IV, ...)
Is a particular version of OpenSSH server and/or client required?
Should the dump be done on the server or client side instead?

I'm interested in feedback from those who have succeeded.

thank you

**Comment by jellever** [comment]
Hey,
You do have an open SSH session on the moment you are creating the memory dump? It shouldn't really matter which version of OpenSSH you are running, as the structure hasn't changed in a while and I account for the differences in older versions. Doesn't matter if you run it on the client or server, it should work in both cases. Are you scanning all processes using the plugin or only certain processes?
Regards,
Jelle

**Comment by dfirtest** [comment]
Thanks for your feedback.
Yes, I perform the dump with the ssh session open. I rather capture from the client to the server. Both have an X11/XFCE interface could that be inconvenient ?
I didn't understand your last point "Are you scanning all processes using the plugin or only certain processes".
I could specify to linux_sshkeys directly the PID to analyze?

**Comment by dfirtest** [comment]
OK thank you for your explanation, it's good for me ;-)
